name: Build and Publish Python Package to Nexus
#reacciona a un push sobre cualquier rama
on:
  push:
    branches:
      - main  # o la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

#intalamos una version de python cualquiera
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build & twine
        run: |
          pip install --upgrade build twine

#toma el codigo y lo lleva a una carpeta
      - name: Build package
        run: |
          python -m build

      - name: List build output  #validacion
        run: |
          ls -la
          ls -la dist

      - name: Upload package to Nexus PyPI
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          twine upload --repository-url "${{ secrets.NEXUS_URL }}" dist/*.tar.gz dist/*.whl
